name: Build EQDiff Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
    
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.0'
    
    - name: Create Build Directory
      run: mkdir build
    
    - name: Configure CMake
      shell: cmd
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_GENERATOR="Visual Studio 17 2022" ^
              -DCMAKE_GENERATOR_PLATFORM=x64 ^
              -DCMAKE_SYSTEM_VERSION=10.0
    
    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release --verbose
    
    - name: List Build Artifacts
      shell: cmd
      run: |
        dir build\EQDiff_artefacts\Release\VST3
        dir build\EQDiff_artefacts\Release\Standalone
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EQDiff-Windows
        path: |
          build/EQDiff_artefacts/Release/VST3/EQDiff.vst3
          build/EQDiff_artefacts/Release/Standalone/EQDiff.exe 