name: Build EQDiff Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.0'
    
    - name: Create Build Directory
      run: mkdir build
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_GENERATOR="Visual Studio 17 2022" ^
              -DCMAKE_GENERATOR_PLATFORM=x64
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EQDiff-Windows
        path: |
          build/EQDiff_artefacts/Release/VST3/EQDiff.vst3
          build/EQDiff_artefacts/Release/Standalone/EQDiff.exe 