name: Windows VST3 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.28.1'
        
    - name: Clean and prepare build directory
      shell: pwsh
      run: |
        if (Test-Path -Path "build") {
          Remove-Item -Path "build" -Recurse -Force
        }
        New-Item -Path "build" -ItemType Directory -Force
        
    - name: Configure CMake
      shell: pwsh
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_EXTRAS=OFF
        
    - name: Build
      shell: pwsh
      run: cmake --build build --config Release --target EQDiff_VST3
      
    - name: List build directory contents
      shell: pwsh
      run: |
        Write-Host "Listing build directory contents:"
        Get-ChildItem -Path "build" -Recurse | Where-Object { $_.Name -like "*.vst3" }
        
    - name: Upload VST3
      uses: actions/upload-artifact@v4
      with:
        name: EQDiff-VST3
        path: build/lib/VST3/EQDiff.vst3/Contents/x86_64-win/EQDiff.vst3
        if-no-files-found: error 